server.port=8081
spring.datasource.url=jdbc:postgresql://localhost:5432/cake_shop_db
spring.datasource.username=postgres
spring.datasource.password=1
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# JSON date format
spring.jackson.serialization.write-dates-as-timestamps=false
spring.jackson.date-format=yyyy-MM-dd HH:mm:ss

# Static resources
spring.web.resources.static-locations=classpath:/static/